
#------------------------------------------------------------
# Section 1: defining objects, binaries and compile-time settings
#------------------------------------------------------------

OBJS = \
		 main.o
	
 
Program			= TagProperty

TARGETS			= aros os3 morphos os4
OBJDIRS			= 
MAKEDIRS			= 

INCOPTS			= 
LIBOPTS			= -lGeneric -lC

AROS_LIBOPTS	= 
M68K_LIBOPTS	= 
MOS_LIBOPTS		= 
OS4_LIBOPTS		= 

BUILD_LIBRARY	= 0

	include ../../../Makefile.mk
